if: tag IS present OR type = pull_request OR (branch = master AND type = push)   # we only CI the master, tags and PRs

language: python
cache: pip
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

services:
  - docker

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install .

script:
  - pytest --cov=alertaclient tests/unit

stages:
  - Hooks
  - Checks
  - Test
  - Integration

jobs:
  include:
    - stage: Hooks
      name: Pre-commit
      script: pre-commit run -a
    - stage: Checks
      name: Lint
      script: pylint --rcfile pylintrc alertaclient
    - name: Type Check
      script: python -m mypy alertaclient/
    - stage: Integration
      name: Integration Test
      script:
      - echo "$GITHUB_TOKEN" | docker login docker.pkg.github.com -u "$DOCKER_USERNAME" --password-stdin
      - docker-compose -f docker-compose.ci.yaml build sut
      - docker-compose -f docker-compose.ci.yaml up --exit-code-from sut
      - docker-compose -f docker-compose.ci.yaml rm --stop --force

after_success:
  - coveralls
